name: Trigger Maven Script

on:
  repository_dispatch:
    types: [trigger-maven]

jobs:
  run-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Maven script
        run: mvn test -DsuiteXmlFile=testng.xml  # Corrected Maven command
